name: Documentation

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[docs]
          sudo apt install pandoc
      - name: Download test data
        run: |
          synthesizer-download --test-grids -d tests/test_grid/
      - name: Sphinx Build
        run: |
          cd docs
          make clean
          make html
          cd ../
      - name: Commit documentation changes
        run: |
          git clone https://github.com/flaresimulations/synthesizer.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}        
