# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Synthesizer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        sudo apt install pandoc
        pip install .[test,docs]
    - uses: chartboost/ruff-action@v1  # Lint with Ruff
    - name: Download test data
      run: |
        # Download test grid data
        synthesizer-download --test-grids -d tests/test_grid/ --dust-grid
    - name: Test with pytest
      run: |
        pytest
        # Test ipython notebooks
        pytest --nbmake docs/source/*.ipynb docs/source/*/*.ipynb
    - name: Sphinx Build
      run: |
        # Test sphinx build (runs all notebooks)
        cd docs
        make clean
        make html
